[package]
name = "jump-jump"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy_hanabi = "0.5.3"
rand = "0.8.0"

[dependencies.bevy]
version = "0.9.1"
features = [
    # TODO 换成symphonia-mp3 https://github.com/bevyengine/bevy/issues/7552
    "mp3"
]